// Generated by https://pagedraw.io/pages/8968
import React from 'react';
import './landing_page.css';

function render() {
    return <div className="landing_page-landing_page-1">
        <div className="landing_page-0">
            <div className="landing_page-0-0">
                <div className="landing_page-0-0-0">
                    <div className="landing_page-careerpad-9">CareerPad</div>
                    <div className="landing_page-0-0-0-1" /> 
                </div>
                <div className="landing_page-0-0-1">
                    <img alt="" src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1534497497827419-1521903569562-6B26C7C1-2E20-4620-B4FD-018F6D356845.png" className="landing_page-line_copy_3" /> 
                    <div className="landing_page-0-0-1-1" /> 
                </div>
                <div className="landing_page-0-0-2">
                    <div className="landing_page-jagongan_media_rakya-1">
                        { this.props.title }
                    </div>
                </div>
                <div className="landing_page-0-0-3">
                    <img alt=""src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1013661666763114-1521903569559-497B3876-DF09-4A19-8353-21614E3EBDA6.png" className="landing_page-line-1" /> 
                    <div className="landing_page-0-0-3-1" /> 
                </div>
                <div className="landing_page-0-0-4">
                    <div className="landing_page-jagongan_media_rakya-8">
                        { this.props.description }
                    </div>
                </div>
                <div className="landing_page-0-0-5">
                    <div className="landing_page-8">{ this.props.date }</div>
                    <div className="landing_page-jogja_national_museu-3">
                        { this.props.venue }
                    </div>
                </div>
                <div className="landing_page-0-0-6">
                    <img alt="" src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1838842677216453-1521903569566-C147A9B3-B1F8-4ED6-8E61-19F7627E735E.png" className="landing_page-line_copy-1" /> 
                    <div className="landing_page-0-0-6-1" /> 
                    <img alt="" src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3006583896507513-1521903569568-FAD45203-525C-4319-A097-653BE0C758AE.png" className="landing_page-line_copy_2" /> 
                    <div className="landing_page-0-0-6-3" /> 
                </div>
                <div className="landing_page-0-0-7">
                    <div className="landing_page-1">{ this.props.time }</div>
                    <div className="landing_page-wirobrajan_jogja_5">
                        { this.props.address }
                    </div>
                </div>
            </div>
            <div className="landing_page-container-1">
                <div className="landing_page-0-1-0">
                    <div className="landing_page-poster_container-5" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                </div>
                <div className="landing_page-0-1-1">
                    <div className="landing_page-form_container-1">
                        <div className="landing_page-0-1-1-0-0">
                            <div className="landing_page-simply_drop_your_ema-1">
                                Simply drop your email to register
                            </div>
                        </div>
                        <div className="landing_page-0-1-1-0-1">
                            <div className="landing_page-0-1-1-0-1-0">
                                <input type="text" placeholder="Your email address here" className="landing_page-email_input-6" /> 
                            </div>
                            <div className="landing_page-0-1-1-0-1-1" /> 
                        </div>
                        <div className="landing_page-0-1-1-0-2">
                            <img alt="" src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8581105776428967-1521903571847-322DBDDA-8842-4D48-BDBC-ED68BD3BAD30.png" className="landing_page-line_2" /> 
                        </div>
                        <div className="landing_page-0-1-1-0-3">
                            <div onClick={this.props.handleClick} className="landing_page-register_button-1">
                                <div className="landing_page-0-1-1-0-3-0-0">
                                    <div className="landing_page-register-4">Register</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}